/**
 * Course Domain Entity
 * Framework-agnostic course representation
 * Maps to content.courses table
 */

export interface CourseLocalization {
  languageId: number;
  title: string;
  description?: string;
}

export interface CourseProps {
  courseId: string;
  targetLanguageId: number;
  baseLanguageId: number;
  levelId: number;
  courseCode: string;
  isPublished: boolean;
  coverAssetId?: string;
  createdBy?: string;
  createdAt: Date;
  updatedAt: Date;
  localizations?: CourseLocalization[];
}

export class CourseEntity {
  private props: CourseProps;

  constructor(props: CourseProps) {
    this.props = props;
  }

  // Getters
  get courseId(): string {
    return this.props.courseId;
  }

  get targetLanguageId(): number {
    return this.props.targetLanguageId;
  }

  get baseLanguageId(): number {
    return this.props.baseLanguageId;
  }

  get levelId(): number {
    return this.props.levelId;
  }

  get courseCode(): string {
    return this.props.courseCode;
  }

  get isPublished(): boolean {
    return this.props.isPublished;
  }

  get coverAssetId(): string | undefined {
    return this.props.coverAssetId;
  }

  get createdBy(): string | undefined {
    return this.props.createdBy;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get updatedAt(): Date {
    return this.props.updatedAt;
  }

  get localizations(): CourseLocalization[] {
    return this.props.localizations || [];
  }

  // Business Methods
  getTitle(languageId: number): string | undefined {
    const localization = this.localizations.find(
      (l) => l.languageId === languageId,
    );
    return localization?.title;
  }

  getDescription(languageId: number): string | undefined {
    const localization = this.localizations.find(
      (l) => l.languageId === languageId,
    );
    return localization?.description;
  }

  canPublish(): boolean {
    // Basic validation - must have at least one localization
    return this.localizations.length > 0;
  }

  // Factory method for creating new course
  static create(
    props: Omit<CourseProps, 'courseId' | 'createdAt' | 'updatedAt'>,
  ): CourseEntity {
    return new CourseEntity({
      ...props,
      courseId: '', // Will be generated by database
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  // Convert to plain object for serialization
  toObject(): CourseProps {
    return { ...this.props };
  }
}
